POST {{host}}/api/sms/verify-and-register
Content-Type: application/json

{
    "name": "nicolas alahmar",
    "email": "nicolasalahmar4@gmail.com",
    "password": "password",
    "password_confirmation": "password",
    "mobile": "0935589733",
    "gender": "male",
    "verification_code": "5666"
}
> {%
client.global.set("user_token", response.body.token);
    client.test("status code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
